package com.Technion.TEDTalkRAGAssistant.dtos;

import lombok.Data;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;

@Component
@Scope("prototype")
@Data
public class TEDTalk {
    private List<TEDTalkChunk> chunks;

    //getters and setters can be generated by Lombok's @Data

}